import type { ArchetypeProfile, CategoryKey } from "./types";

export const CATEGORY_LABELS: Record<CategoryKey, string> = {
  preflopDiscipline: "Preflop Discipline",
  initiative: "Initiative",
  positionUse: "Position Use",
  archetypeAdjustment: "Archetype Adjustment",
  sizing: "Sizing",
  valueShowdown: "Value / Showdown",
  riskControl: "Risk Control",
  coherence: "Line Coherence",
};

export const ARCHETYPES: Record<string, ArchetypeProfile> = {
  Nit: {
    name: "Nit",
    foldTendency: 0.86,
    callTendency: 0.18,
    bluffTendency: 0.16,
    aggressionTendency: 0.28,
    showdownTendency: 0.32,
    elasticityVsPressure: 0.84,
    valueOwningRisk: 0.22,
    trapFrequency: 0.35,
    description: "Overfolds under heat, arrives strong, rarely spews.",
  },
  TAG: {
    name: "TAG",
    foldTendency: 0.56,
    callTendency: 0.34,
    bluffTendency: 0.3,
    aggressionTendency: 0.55,
    showdownTendency: 0.46,
    elasticityVsPressure: 0.58,
    valueOwningRisk: 0.42,
    trapFrequency: 0.32,
    description: "Balanced baseline opponent with solid ranges.",
  },
  LAG: {
    name: "LAG",
    foldTendency: 0.48,
    callTendency: 0.37,
    bluffTendency: 0.64,
    aggressionTendency: 0.76,
    showdownTendency: 0.41,
    elasticityVsPressure: 0.46,
    valueOwningRisk: 0.5,
    trapFrequency: 0.24,
    description: "Applies pressure wide and challenges capped lines.",
  },
  "Calling Station": {
    name: "Calling Station",
    foldTendency: 0.16,
    callTendency: 0.88,
    bluffTendency: 0.08,
    aggressionTendency: 0.24,
    showdownTendency: 0.84,
    elasticityVsPressure: 0.14,
    valueOwningRisk: 0.76,
    trapFrequency: 0.12,
    description: "Sticky target that rewards value and punishes empty barrels.",
  },
  Maniac: {
    name: "Maniac",
    foldTendency: 0.36,
    callTendency: 0.44,
    bluffTendency: 0.92,
    aggressionTendency: 0.94,
    showdownTendency: 0.39,
    elasticityVsPressure: 0.31,
    valueOwningRisk: 0.58,
    trapFrequency: 0.18,
    description: "Hyper-aggressive profile that invites trapping and discipline.",
  },
  Unknown: {
    name: "Unknown",
    foldTendency: 0.5,
    callTendency: 0.4,
    bluffTendency: 0.3,
    aggressionTendency: 0.45,
    showdownTendency: 0.45,
    elasticityVsPressure: 0.48,
    valueOwningRisk: 0.45,
    trapFrequency: 0.2,
    description: "Fallback profile when export data is partial.",
  },
};

export const MODE_WEIGHTS = {
  sound_fundamentals: {
    preflopDiscipline: 1.35,
    initiative: 1.15,
    positionUse: 1.05,
    archetypeAdjustment: 1,
    sizing: 1,
    valueShowdown: 1,
    riskControl: 1.2,
    coherence: 1.1,
  },
  adaptive_pressure: {
    preflopDiscipline: 1.15,
    initiative: 1.2,
    positionUse: 1.05,
    archetypeAdjustment: 1.35,
    sizing: 1.05,
    valueShowdown: 1,
    riskControl: 1.15,
    coherence: 1.15,
  },
} as const;

export const CATEGORY_KEYS = Object.keys(CATEGORY_LABELS) as CategoryKey[];
